name: Python CI and Docker Image Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install flake8 pytest

    - name: Lint code with flake8
      run: |
        flake8 .

    - name: Login Resigtry
        if: github.event_name == 'push'
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          - name: Build
            run: |
              docker build -t lyleshaw/gradio-test -f ./Dockerfile . 
              docker push lyleshaw/gradio-test:latest
